version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/shared-types"
    schedule:
      interval: "weekly"
