import type { AssetSearchRow } from 'shared-types'

export function makeAssetSearchRow(overrides: Partial<AssetSearchRow> = {}): AssetSearchRow {
  return {
    id: 1,
    barcode: 'BC-1',
    brand: 'CANON',
    model: 'IR-2020',
    asset_type: 'COPIER',
    serial_number: 'SN-1',
    status: 'IN_STOCK',
    readiness: 'PP_OK',
    location: null,
    is_in_transit: false,
    created_at: new Date('2026-01-01T00:00:00Z'),
    country_of_origin: null,
    manufactured_year: null,
    weight: 0,
    size: 0,
    specs_meter_total: 0,
    specs_cassettes: null,
    specs_internal_finisher: null,
    accessories: [],
    specs_toner_life_c: null,
    specs_toner_life_m: null,
    specs_toner_life_y: null,
    specs_toner_life_k: null,
    cost_purchase_cost: 100,
    cost_transport_cost: 20,
    cost_processing_cost: 5,
    cost_other_cost: 0,
    cost_parts_cost: 0,
    cost_total_cost: 125,
    cost_sale_price: 200,
    hold_hold_number: null,
    held_by: null,
    hold_created_for: null,
    hold_customer: null,
    hold_created_at: null,
    vendor: null,
    customer: null,
    departed_at: null,
    arrival_created_at: null,
    purchase_invoice_invoice_number: null,
    purchase_invoice_invoice_reference: null,
    sales_invoice_invoice_number: null,
    sales_invoice_invoice_reference: null,
    latest_comment: null,
    latest_comment_by: null,
    latest_comment_at: null,
    ...overrides,
  }
}
