CREATE TABLE "Role" (
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "is_system" BOOLEAN NOT NULL DEFAULT false,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "Role_pkey" PRIMARY KEY ("code")
);

CREATE UNIQUE INDEX "Role_name_key" ON "Role"("name");

CREATE TABLE "Permission" (
    "key" TEXT NOT NULL,
    CONSTRAINT "Permission_pkey" PRIMARY KEY ("key")
);

CREATE TABLE "RolePermission" (
    "role_code" TEXT NOT NULL,
    "permission_key" TEXT NOT NULL,
    CONSTRAINT "RolePermission_pkey" PRIMARY KEY ("role_code", "permission_key")
);

CREATE INDEX "RolePermission_permission_key_idx" ON "RolePermission"("permission_key");

ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_role_code_fkey"
    FOREIGN KEY ("role_code") REFERENCES "Role"("code") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_permission_key_fkey"
    FOREIGN KEY ("permission_key") REFERENCES "Permission"("key") ON DELETE CASCADE ON UPDATE CASCADE;

-- Seeded from the ROLE_PERMISSIONS constant this migration replaces.
INSERT INTO "Permission" ("key") VALUES
    ('view_asset'),
    ('view_collections'),
    ('view_reports'),
    ('view_store'),
    ('create_update_arrival'),
    ('create_update_hold'),
    ('create_update_transfer'),
    ('create_update_departure'),
    ('create_update_invoice'),
    ('create_update_store'),
    ('update_tech_specs'),
    ('update_location'),
    ('update_settings'),
    ('return_to_stock'),
    ('view_sale_price'),
    ('view_purchase_price'),
    ('edit_any_hold'),
    ('edit_prices'),
    ('view_profitability_report'),
    ('update_users'),
    ('update_user_roles'),
    ('delete_asset'),
    ('delete_collection');

INSERT INTO "Role" ("code", "name", "is_system", "is_default") VALUES
    ('admin', 'Admin', true, false),
    ('leadership', 'Leadership', false, false),
    ('general_manager', 'General Manager', false, false),
    ('inventory_manager', 'Inventory Manager', false, false),
    ('branch_manager', 'Branch Manager', false, false),
    ('senior_sales', 'Senior Sales', false, false),
    ('sales', 'Sales', false, false),
    ('shipping', 'Shipping', false, false),
    ('senior_accountant', 'Senior Accountant', false, false),
    ('accountant', 'Accountant', false, false),
    ('tech', 'Tech', false, false),
    ('sales_assistant', 'Sales Assistant', false, false),
    ('picker', 'Picker', false, false),
    ('member', 'Member', false, true);

INSERT INTO "RolePermission" ("role_code", "permission_key") VALUES
    ('admin', 'view_asset'),
    ('admin', 'view_collections'),
    ('admin', 'view_reports'),
    ('admin', 'view_store'),
    ('admin', 'create_update_arrival'),
    ('admin', 'create_update_hold'),
    ('admin', 'create_update_transfer'),
    ('admin', 'create_update_departure'),
    ('admin', 'create_update_invoice'),
    ('admin', 'create_update_store'),
    ('admin', 'update_tech_specs'),
    ('admin', 'update_location'),
    ('admin', 'update_settings'),
    ('admin', 'return_to_stock'),
    ('admin', 'view_sale_price'),
    ('admin', 'view_purchase_price'),
    ('admin', 'edit_any_hold'),
    ('admin', 'edit_prices'),
    ('admin', 'view_profitability_report'),
    ('admin', 'update_users'),
    ('admin', 'update_user_roles'),
    ('admin', 'delete_asset'),
    ('admin', 'delete_collection'),
    ('leadership', 'view_asset'),
    ('leadership', 'view_collections'),
    ('leadership', 'view_reports'),
    ('leadership', 'view_store'),
    ('leadership', 'create_update_arrival'),
    ('leadership', 'create_update_hold'),
    ('leadership', 'create_update_transfer'),
    ('leadership', 'create_update_departure'),
    ('leadership', 'create_update_invoice'),
    ('leadership', 'create_update_store'),
    ('leadership', 'update_tech_specs'),
    ('leadership', 'update_location'),
    ('leadership', 'return_to_stock'),
    ('leadership', 'view_sale_price'),
    ('leadership', 'view_purchase_price'),
    ('leadership', 'edit_any_hold'),
    ('leadership', 'edit_prices'),
    ('leadership', 'view_profitability_report'),
    ('general_manager', 'view_asset'),
    ('general_manager', 'view_collections'),
    ('general_manager', 'view_reports'),
    ('general_manager', 'view_store'),
    ('general_manager', 'create_update_arrival'),
    ('general_manager', 'create_update_hold'),
    ('general_manager', 'create_update_transfer'),
    ('general_manager', 'create_update_departure'),
    ('general_manager', 'create_update_invoice'),
    ('general_manager', 'create_update_store'),
    ('general_manager', 'update_tech_specs'),
    ('general_manager', 'update_location'),
    ('general_manager', 'return_to_stock'),
    ('general_manager', 'view_sale_price'),
    ('general_manager', 'view_purchase_price'),
    ('general_manager', 'edit_any_hold'),
    ('general_manager', 'edit_prices'),
    ('inventory_manager', 'view_asset'),
    ('inventory_manager', 'view_collections'),
    ('inventory_manager', 'view_reports'),
    ('inventory_manager', 'view_store'),
    ('inventory_manager', 'create_update_arrival'),
    ('inventory_manager', 'create_update_hold'),
    ('inventory_manager', 'create_update_transfer'),
    ('inventory_manager', 'create_update_departure'),
    ('inventory_manager', 'create_update_invoice'),
    ('inventory_manager', 'create_update_store'),
    ('inventory_manager', 'update_tech_specs'),
    ('inventory_manager', 'update_location'),
    ('inventory_manager', 'update_settings'),
    ('inventory_manager', 'return_to_stock'),
    ('inventory_manager', 'view_sale_price'),
    ('inventory_manager', 'view_purchase_price'),
    ('inventory_manager', 'edit_any_hold'),
    ('inventory_manager', 'edit_prices'),
    ('branch_manager', 'view_asset'),
    ('branch_manager', 'view_collections'),
    ('branch_manager', 'view_reports'),
    ('branch_manager', 'view_store'),
    ('branch_manager', 'create_update_arrival'),
    ('branch_manager', 'create_update_hold'),
    ('branch_manager', 'create_update_transfer'),
    ('branch_manager', 'create_update_departure'),
    ('branch_manager', 'create_update_invoice'),
    ('branch_manager', 'create_update_store'),
    ('branch_manager', 'update_tech_specs'),
    ('branch_manager', 'update_location'),
    ('branch_manager', 'view_sale_price'),
    ('branch_manager', 'view_purchase_price'),
    ('senior_sales', 'view_asset'),
    ('senior_sales', 'view_collections'),
    ('senior_sales', 'view_reports'),
    ('senior_sales', 'create_update_hold'),
    ('senior_sales', 'view_sale_price'),
    ('senior_sales', 'view_purchase_price'),
    ('sales', 'view_asset'),
    ('sales', 'view_collections'),
    ('sales', 'view_reports'),
    ('sales', 'create_update_hold'),
    ('sales', 'view_sale_price'),
    ('shipping', 'view_asset'),
    ('shipping', 'view_collections'),
    ('shipping', 'view_store'),
    ('shipping', 'create_update_arrival'),
    ('shipping', 'create_update_transfer'),
    ('shipping', 'create_update_departure'),
    ('shipping', 'create_update_store'),
    ('shipping', 'update_tech_specs'),
    ('shipping', 'update_location'),
    ('senior_accountant', 'view_asset'),
    ('senior_accountant', 'view_collections'),
    ('senior_accountant', 'view_reports'),
    ('senior_accountant', 'view_store'),
    ('senior_accountant', 'create_update_arrival'),
    ('senior_accountant', 'create_update_hold'),
    ('senior_accountant', 'create_update_transfer'),
    ('senior_accountant', 'create_update_departure'),
    ('senior_accountant', 'create_update_invoice'),
    ('senior_accountant', 'update_tech_specs'),
    ('senior_accountant', 'view_sale_price'),
    ('senior_accountant', 'view_purchase_price'),
    ('senior_accountant', 'edit_any_hold'),
    ('senior_accountant', 'edit_prices'),
    ('accountant', 'view_asset'),
    ('accountant', 'view_collections'),
    ('accountant', 'view_store'),
    ('accountant', 'view_sale_price'),
    ('accountant', 'create_update_invoice'),
    ('accountant', 'view_purchase_price'),
    ('accountant', 'edit_prices'),
    ('tech', 'view_asset'),
    ('tech', 'view_collections'),
    ('tech', 'view_store'),
    ('tech', 'create_update_store'),
    ('tech', 'update_tech_specs'),
    ('tech', 'update_location'),
    ('sales_assistant', 'view_asset'),
    ('sales_assistant', 'view_collections'),
    ('sales_assistant', 'create_update_hold'),
    ('sales_assistant', 'edit_any_hold'),
    ('sales_assistant', 'create_update_invoice'),
    ('picker', 'view_asset'),
    ('picker', 'view_collections'),
    ('picker', 'update_location'),
    ('member', 'view_asset'),
    ('member', 'view_collections');

-- Every existing User.role value must already be a seeded Role.code for this to hold.
ALTER TABLE "User" ADD CONSTRAINT "User_role_fkey"
    FOREIGN KEY ("role") REFERENCES "Role"("code") ON DELETE RESTRICT ON UPDATE RESTRICT;
